apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appgroup: ""
    version: v1
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - env:
        - name: PAAS_APP_NAME
          value: backend
        - name: PAAS_NAMESPACE
          value: default
        - name: PAAS_PROJECT_ID
          value: 0b8707102c00109a2ff2c0052b69535c
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DB
              name: db-access
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: db-access
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: db-access
        - name: MYSQL_PASSWD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWD
              name: db-password
        image: swr.la-south-2.myhuaweicloud.com/demo-huawei/backend:v1.0
        imagePullPolicy: Always
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsConfig:
        options:
        - name: timeout
          value: ""
        - name: ndots
          value: "5"
        - name: single-request-reopen
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
