apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: cce-service-0
    nodePort: 31259
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: backend
  sessionAffinity: None
  type: NodePort
