apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: SSD
    volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    failure-domain.beta.kubernetes.io/region: la-south-2
    failure-domain.beta.kubernetes.io/zone: la-south-2b
  name: mysql-pv-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-disk
