apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
        - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Dcb6Hn9Qw2MkG0Pi0S2qJf#
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - mountPath: /opt/poststart.sh
          subPath: poststart.sh
          name: hookvolume
        - mountPath: /docker-entrypoint-initdb.d/script.sql
          subPath: script.sql
          name: hookvolume
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: hookvolume
        configMap:
          name: poststarthook
          defaultMode: 0755 #please remember to add proper (executable) permissions
